# Generated by Django 3.2 on 2021-04-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_driver', '0002_alter_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="name",
            field=models.CharField(max_length=200),
        ),
    ]
