# Generated by Django 4.1.5 on 2023-01-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample_driver', '0002_alter_driver_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverFlag',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                )),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='flags',
            field=models.ManyToManyField(to='sample_driver.driverflag'),
        ),
    ]
