# Generated by Django 2.2 on 2019-11-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0003_book_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
