# Generated by Django 3.0 on 2019-12-03 09:47

from django.db import migrations, models
import django.db.models.deletion
import model_clone.mixins.clone


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0004_auto_20191122_0848"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=20000)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="sample.Book",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(model_clone.mixins.clone.CloneMixin, models.Model),
        ),
    ]
