# Generated by Django 3.0.4 on 2020-08-29 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0006_assignment"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="author",
            unique_together={("first_name", "last_name", "sex")},
        ),
    ]
