# Generated by Django 3.0.6 on 2020-05-16 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample_company', '0001_initial'),
        ('sample_driver', '0001_initial'),
        ('sample_assignment', '0001_initial'),
        ('sample', '0006_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='applied_drivers',
            field=models.ManyToManyField(blank=True, related_name='driver_applications', to='sample_driver.Driver', verbose_name='Driver applications'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='chosen_drivers',
            field=models.ManyToManyField(blank=True, to='sample_driver.Driver', verbose_name='Chosen drivers'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sample_company.CompanyDepot', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_contracts', to='sample_assignment.Contract', verbose_name='Choose contract'),
        ),
    ]
