# Generated by Django 3.1.7 on 2021-04-07 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0007_auto_20200829_0213"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
