# Generated by Django 3.1.7 on 2021-04-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0008_page_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="library",
            options={"verbose_name_plural": "libraries"},
        ),
    ]
