# Generated by Django 3.1.5 on 2021-04-13 02:59

from django.db import migrations, models
import django.db.models.deletion
import model_clone.mixins.clone


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0009_auto_20210407_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sample.book')),
            ],
            options={
                'abstract': False,
            },
            bases=(model_clone.mixins.clone.CloneMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BackCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sample.book')),
            ],
        ),
    ]
