# Generated by Django 3.1.5 on 2021-04-20 00:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import model_clone.mixins.clone


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0012_backcover_cover"),
    ]

    operations = [
        migrations.CreateModel(
            name="Edition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editions",
                        to="sample.book",
                    ),
                ),
            ],
            bases=(model_clone.mixins.clone.CloneMixin, models.Model),
        ),
    ]
