# Generated by Django 3.2.5 on 2021-07-17 22:30
import django
from django.db import migrations, models

import sample.models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0019_saletag_sale_tag_unique_name"),
    ]

    operations = (
        [
            migrations.AlterField(
                model_name="tag",
                name="name",
                field=models.CharField(
                    default=sample.models.get_unique_tag_name, max_length=255
                ),
            ),
            migrations.AddConstraint(
                model_name="tag",
                constraint=models.UniqueConstraint(
                    fields=("name",), name="tag_unique_name"
                ),
            ),
        ]
        if django.VERSION >= (2, 2)
        else [
            migrations.AlterField(
                model_name="tag",
                name="name",
                field=models.CharField(
                    default=sample.models.get_unique_tag_name,
                    max_length=255,
                    unique=True,
                ),
            ),
        ]
    )
