# Generated by Django 3.2.6 on 2021-08-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0019_saletag_sale_tag_unique_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="custom_slug",
            field=models.SlugField(default=""),
        ),
    ]
