# Generated by Django 4.0.2 on 2022-02-11 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0022_ending_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='lives_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sample.house'),
        ),
        migrations.AddField(
            model_name='book',
            name='found_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='sample.furniture'),
        ),
    ]
