# Generated by Django 3.2.13 on 2022-06-24 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0023_alter_edition_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edition",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="editions",
                to="sample.book",
            ),
        ),
    ]
