# Generated by Django 4.0.2 on 2022-04-07 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0024_cover_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='owned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sample.author'),
        ),
    ]
